name: Lint & Format

on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'Terraform version'
        type: string
        default: '1.6.0'
        required: false
      tflint_config:
        description: 'Path to .tflint.hcl config file'
        type: string
        default: '.tflint.hcl'
        required: false

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: TFLint Init
        run: tflint --init --config=${{ inputs.tflint_config }}

      - name: TFLint Run
        run: tflint --recursive --config=${{ inputs.tflint_config }}
