name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  auto-tag:
    uses: praxis-terraform-modules/terraform-cicd-templates/.github/workflows/auto-tag.yml@main
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
